import type { ImportedCompetition } from "./import-types";

export const sampleWorldCupData: ImportedCompetition = {
  name: "Copa do Mundo FIFA",
  year: 2026,
  api_source: "manual-sample",
  api_competition_id: "fifa-world-cup-2026",
  teams: [
    {
      api_team_id: "BRA",
      name: "Brasil",
      country_code: "BR",
      fifa_code: "BRA",
    },
    {
      api_team_id: "ARG",
      name: "Argentina",
      country_code: "AR",
      fifa_code: "ARG",
    },
    {
      api_team_id: "FRA",
      name: "França",
      country_code: "FR",
      fifa_code: "FRA",
    },
    {
      api_team_id: "GER",
      name: "Alemanha",
      country_code: "DE",
      fifa_code: "GER",
    },
    {
      api_team_id: "ESP",
      name: "Espanha",
      country_code: "ES",
      fifa_code: "ESP",
    },
    {
      api_team_id: "ENG",
      name: "Inglaterra",
      country_code: "GB",
      fifa_code: "ENG",
    },
    {
      api_team_id: "POR",
      name: "Portugal",
      country_code: "PT",
      fifa_code: "POR",
    },
    {
      api_team_id: "URU",
      name: "Uruguai",
      country_code: "UY",
      fifa_code: "URU",
    },
    {
      api_team_id: "MAR",
      name: "Marrocos",
      country_code: "MA",
      fifa_code: "MAR",
    },
    {
      api_team_id: "JPN",
      name: "Japão",
      country_code: "JP",
      fifa_code: "JPN",
    },
  ],
  matches: [
    {
      api_match_id: "sample-001",
      stage: "group",
      home_team_api_id: "BRA",
      away_team_api_id: "ARG",
      kickoff_at: "2026-07-10T19:00:00-03:00",
      venue: "Estádio Teste 1",
      city: "Cidade Teste",
      status: "scheduled",
    },
    {
      api_match_id: "sample-002",
      stage: "group",
      home_team_api_id: "FRA",
      away_team_api_id: "GER",
      kickoff_at: "2026-07-11T16:00:00-03:00",
      venue: "Estádio Teste 2",
      city: "Cidade Teste",
      status: "scheduled",
    },
    {
      api_match_id: "sample-003",
      stage: "group",
      home_team_api_id: "ESP",
      away_team_api_id: "ENG",
      kickoff_at: "2026-07-05T16:00:00-03:00",
      venue: "Estádio Teste 3",
      city: "Cidade Teste",
      status: "finished",
      home_score: 2,
      away_score: 1,
      winner_team_api_id: "ESP",
    },
    {
      api_match_id: "sample-004",
      stage: "group",
      home_team_api_id: "POR",
      away_team_api_id: "URU",
      kickoff_at: "2026-07-04T16:00:00-03:00",
      venue: "Estádio Teste 4",
      city: "Cidade Teste",
      status: "finished",
      home_score: 1,
      away_score: 1,
    },
    {
      api_match_id: "sample-005",
      stage: "round_of_16",
      home_team_api_id: "BRA",
      away_team_api_id: "JPN",
      kickoff_at: "2026-07-12T18:00:00-03:00",
      venue: "Estádio Teste 5",
      city: "Cidade Teste",
      status: "scheduled",
      bracket_position: "R16-1",
    },
    {
      api_match_id: "sample-006",
      stage: "round_of_16",
      home_team_api_id: "FRA",
      away_team_api_id: "MAR",
      kickoff_at: "2026-07-13T18:00:00-03:00",
      venue: "Estádio Teste 6",
      city: "Cidade Teste",
      status: "scheduled",
      bracket_position: "R16-2",
    },
  ],
};
